[package]
name = "binary_enclave"
version = "0.1.0"
authors = ["Zachery Hostens <zacheryph@gmail.com>"]
edition = "2018"
categories = ["config"]

[dependencies]
bincode = "1.3.1"
binary_enclave_macro = { version = "=0.1.0", path = "macro" }
goblin = "0.2.3"
serde = "1.0.114"
thiserror = "1.0.20"
